#!/bin/bash
echo "Cloning repository"
git clone https://github.com/studioraz/magento-config-bootstrap.git

echo "moving config folder under Magento root" 
mv magento-config-bootstrap/config ./

echo "deleting repository folder"
rm -rf magento-config-bootstrap

echo "done"