#########
# general
#########
general/country/default:
  default:
    '0': IL
general/country/allow:
  default:
    '0': IL
general/locale/timezone:
  default:
    '0': Asia/Jerusalem
general/locale/code:
  default:
    '0': he_IL
general/locale/weight_unit:
  default:
    '0': kgs
general/locale/weekend:
  default:
    '0': 5,6
general/single_store_mode/enabled:
  default:
    '0': '1'
general/country/optional_zip_countries:
  default:
    '0': IL
general/store_information/city:
  default:
    0: ''
general/store_information/country_id:
  default:
    0: 'IL'
general/store_information/hours:
  default:
    0: ''
general/store_information/merchant_vat_number:
  default:
    0: ''
general/store_information/name:
  default:
    0: ''
general/store_information/phone:
  default:
    0: ''
general/store_information/postcode:
  default:
    0: ''
general/store_information/region_id:
  default:
    0: ''
general/store_information/street_line1:
  default:
    0: ''
general/store_information/street_line2:
  default:
    0: ''
